packages:
  - frontend
  - remote-frontend

onlyBuiltDependencies:
  - '@sentry/cli'
  - core-js
  - esbuild
patchedDependencies:
  '@virtuoso.dev/message-list@1.13.3': patches/@virtuoso.dev__message-list@1.13.3.patch
